/**
 * Narrow, forward-compatible Codex app-server protocol types.
 *
 * These shapes were checked against the TypeScript schema generated by
 * `codex app-server generate-ts` from codex-cli 0.146.0.  The app-server
 * protocol evolves with the CLI, so objects deliberately retain unknown
 * properties and unknown methods remain legal at the RPC boundary.
 */

export type CodexRpcId = number | string

export type CodexRpcError = {
  code: number
  message: string
  data?: unknown
}

export type CodexRpcRequest = {
  method: string
  id: CodexRpcId
  params?: unknown
}

export type CodexRpcNotification = {
  method: string
  params?: unknown
}

export type CodexRpcResponse = {
  id: CodexRpcId
  result?: unknown
  error?: CodexRpcError
}

export type CodexWireMessage = CodexRpcRequest | CodexRpcNotification | CodexRpcResponse

export type CodexClientInfo = {
  name: string
  title: string
  version: string
}

export type CodexInitializeParams = {
  clientInfo: CodexClientInfo
  capabilities: {
    experimentalApi?: boolean
    optOutNotificationMethods?: string[]
    requestAttestation?: boolean
    mcpServerOpenaiFormElicitation?: boolean
    [key: string]: unknown
  } | null
}

export type CodexInitializeResponse = {
  userAgent: string
  codexHome: string
  platformFamily: string
  platformOs: string
  [key: string]: unknown
}

export type CodexApprovalPolicy =
  | 'untrusted'
  | 'on-request'
  | 'never'
  | {
    granular: {
      sandbox_approval: boolean
      rules: boolean
      skill_approval: boolean
      request_permissions: boolean
      mcp_elicitations: boolean
    }
  }

export type CodexSandboxMode = 'read-only' | 'workspace-write' | 'danger-full-access'

export type CodexThreadStatus =
  | { type: 'notLoaded' }
  | { type: 'idle' }
  | { type: 'systemError' }
  | { type: 'active'; activeFlags: unknown[] }
  | { type: string; [key: string]: unknown }

export type CodexTurnStatus = 'completed' | 'interrupted' | 'failed' | 'inProgress' | string

export type CodexThreadItem = {
  type: string
  id?: string
  [key: string]: unknown
}

export type CodexTurn = {
  id: string
  items: CodexThreadItem[]
  status: CodexTurnStatus
  error: unknown | null
  startedAt?: number | null
  completedAt?: number | null
  durationMs?: number | null
  [key: string]: unknown
}

export type CodexThread = {
  id: string
  /**
   * Provider session identity. Do not infer native fork lineage from
   * sessionId equality; forkedFromId is the lineage authority.
   */
  sessionId?: string
  parentThreadId?: string | null
  forkedFromId?: string | null
  preview?: string
  ephemeral?: boolean
  modelProvider?: string
  createdAt?: number
  updatedAt?: number
  status: CodexThreadStatus
  cwd: string
  cliVersion?: string
  agentNickname?: string | null
  agentRole?: string | null
  name?: string | null
  turns: CodexTurn[]
  [key: string]: unknown
}

export type CodexTextInput = {
  type: 'text'
  text: string
  text_elements: unknown[]
}

export type CodexUserInput = CodexTextInput | {
  type: string
  [key: string]: unknown
}

export type CodexThreadStartParams = {
  model?: string | null
  modelProvider?: string | null
  serviceTier?: string | null
  cwd?: string | null
  approvalPolicy?: CodexApprovalPolicy | null
  approvalsReviewer?: unknown
  sandbox?: CodexSandboxMode | null
  config?: Record<string, unknown> | null
  serviceName?: string | null
  baseInstructions?: string | null
  developerInstructions?: string | null
  personality?: string | null
  ephemeral?: boolean | null
  sessionStartSource?: unknown
  threadSource?: unknown
}

export type CodexThreadStartResponse = {
  thread: CodexThread
  model: string
  modelProvider: string
  serviceTier: string | null
  cwd: string
  instructionSources: string[]
  approvalPolicy: CodexApprovalPolicy
  approvalsReviewer: unknown
  sandbox: unknown
  reasoningEffort: string | null
  [key: string]: unknown
}

export type CodexThreadResumeParams = CodexThreadStartParams & {
  threadId: string
}

export type CodexThreadResumeResponse = CodexThreadStartResponse

/**
 * Exact `thread/fork` request surface supported by Codex CLI 0.146.0.
 *
 * The runtime driver deliberately exposes a narrower fork primitive so Agent
 * Home cannot replace source provenance through the unstable path override.
 */
export type CodexThreadForkParams = {
  threadId: string
  lastTurnId?: string | null
  path?: string | null
  model?: string | null
  modelProvider?: string | null
  serviceTier?: string | null
  cwd?: string | null
  runtimeWorkspaceRoots?: string[] | null
  approvalPolicy?: CodexApprovalPolicy | null
  approvalsReviewer?: unknown
  sandbox?: CodexSandboxMode | null
  permissions?: string | null
  config?: Record<string, unknown> | null
  baseInstructions?: string | null
  developerInstructions?: string | null
  ephemeral?: boolean
  threadSource?: unknown
  excludeTurns?: boolean
}

export type CodexThreadForkResponse = {
  thread: CodexThread
  model: string
  modelProvider: string
  serviceTier: string | null
  cwd: string
  runtimeWorkspaceRoots: string[]
  instructionSources: string[]
  approvalPolicy: CodexApprovalPolicy
  approvalsReviewer: unknown
  sandbox: unknown
  activePermissionProfile: unknown | null
  reasoningEffort: string | null
  multiAgentMode: unknown
  [key: string]: unknown
}

export type CodexThreadReadParams = {
  threadId: string
  includeTurns?: boolean
}

export type CodexThreadReadResponse = {
  thread: CodexThread
}

export type CodexThreadUnsubscribeResponse = {
  status: string
}

export type CodexTurnStartParams = {
  threadId: string
  clientUserMessageId?: string | null
  input: CodexUserInput[]
  cwd?: string | null
  approvalPolicy?: CodexApprovalPolicy | null
  approvalsReviewer?: unknown
  sandboxPolicy?: unknown
  model?: string | null
  serviceTier?: string | null
  effort?: string | null
  summary?: string | null
  personality?: string | null
  outputSchema?: unknown
}

export type CodexTurnStartResponse = {
  turn: CodexTurn
}

export type CodexTurnSteerParams = {
  threadId: string
  clientUserMessageId?: string | null
  input: CodexUserInput[]
  expectedTurnId: string
}

export type CodexTurnSteerResponse = {
  turnId: string
}

export type CodexModel = {
  id: string
  model: string
  displayName: string
  description: string
  hidden: boolean
  supportedReasoningEfforts: Array<{ reasoningEffort: string; description: string }>
  defaultReasoningEffort: string
  inputModalities: string[]
  supportsPersonality: boolean
  serviceTiers: unknown[]
  defaultServiceTier: string | null
  isDefault: boolean
  [key: string]: unknown
}

export type CodexModelListResponse = {
  data: CodexModel[]
  nextCursor: string | null
}

export type CodexAccount =
  | { type: 'apiKey'; [key: string]: unknown }
  | { type: 'chatgpt'; email: string | null; planType: string; [key: string]: unknown }
  | { type: 'amazonBedrock'; usesCodexManagedCredentials: boolean; [key: string]: unknown }
  | { type: string; [key: string]: unknown }

export type CodexAccountResponse = {
  account: CodexAccount | null
  requiresOpenaiAuth: boolean
}

export type CodexRateLimitWindow = {
  usedPercent: number
  windowDurationMins: number | null
  resetsAt: number | null
}

export type CodexRateLimitSnapshot = {
  limitId: string | null
  limitName: string | null
  primary: CodexRateLimitWindow | null
  secondary: CodexRateLimitWindow | null
  credits: unknown | null
  individualLimit: unknown | null
  spendControlReached: boolean | null
  planType: string | null
  rateLimitReachedType: unknown | null
  [key: string]: unknown
}

export type CodexRateLimitsResponse = {
  rateLimits: CodexRateLimitSnapshot
  rateLimitsByLimitId: Record<string, CodexRateLimitSnapshot> | null
  rateLimitResetCredits: unknown | null
}

export type CodexAccountUsageResponse = {
  summary: {
    lifetimeTokens: number | string | null
    peakDailyTokens: number | string | null
    longestRunningTurnSec: number | string | null
    currentStreakDays: number | string | null
    longestStreakDays: number | string | null
    [key: string]: unknown
  }
  dailyUsageBuckets: Array<{ startDate: string; tokens: number | string }> | null
}

export type CodexTokenUsageBreakdown = {
  totalTokens: number
  inputTokens: number
  cachedInputTokens: number
  outputTokens: number
  reasoningOutputTokens: number
}

export type CodexThreadTokenUsage = {
  total: CodexTokenUsageBreakdown
  last: CodexTokenUsageBreakdown
  modelContextWindow: number | null
}

export type CodexAppServerMethodMap = {
  initialize: { params: CodexInitializeParams; result: CodexInitializeResponse }
  'thread/start': { params: CodexThreadStartParams; result: CodexThreadStartResponse }
  'thread/resume': { params: CodexThreadResumeParams; result: CodexThreadResumeResponse }
  'thread/fork': { params: CodexThreadForkParams; result: CodexThreadForkResponse }
  'thread/read': { params: CodexThreadReadParams; result: CodexThreadReadResponse }
  'thread/unsubscribe': { params: { threadId: string }; result: CodexThreadUnsubscribeResponse }
  'turn/start': { params: CodexTurnStartParams; result: CodexTurnStartResponse }
  'turn/steer': { params: CodexTurnSteerParams; result: CodexTurnSteerResponse }
  'turn/interrupt': { params: { threadId: string; turnId: string }; result: Record<string, never> }
  'model/list': {
    params: { cursor?: string | null; limit?: number | null; includeHidden?: boolean | null }
    result: CodexModelListResponse
  }
  'account/read': { params: { refreshToken?: boolean }; result: CodexAccountResponse }
  'account/rateLimits/read': { params: undefined; result: CodexRateLimitsResponse }
  'account/usage/read': { params: undefined; result: CodexAccountUsageResponse }
}

export type CodexRpcMethod = keyof CodexAppServerMethodMap

export type CodexMethodParams<M extends string> =
  M extends CodexRpcMethod ? CodexAppServerMethodMap[M]['params'] : unknown

export type CodexMethodResult<M extends string> =
  M extends CodexRpcMethod ? CodexAppServerMethodMap[M]['result'] : unknown

export type CodexServerNotification = {
  method: string
  params: unknown
  receivedAt: string
}

export type CodexServerRequest = {
  id: CodexRpcId
  method: string
  params: unknown
  receivedAt: string
}

export type CodexDiagnostic = {
  source: 'stderr' | 'protocol' | 'transport' | 'supervisor'
  level: 'debug' | 'info' | 'warning' | 'error'
  message: string
  at: string
  metadata?: Record<string, unknown>
}

export const codexTextInput = (text: string): CodexTextInput => ({
  type: 'text',
  text,
  text_elements: [],
})

export const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value)
